apiVersion: v1
kind: Service
metadata:
  name: ocs
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: ocs
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: ocs
  ports:
    - name: http
      port: 9110
      protocol: TCP
    - name: metrics-debug
      port: 9114
      protocol: TCP
