apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ocis-trust
spec:
  sources:
    - secret:
        name: "root-secret"
        key: "ca.crt"
  target:
    configMap:
      key: "my-ca-issuer-root-certs.pem"
