repositories:
  - name: tika
    url: https://apache.jfrog.io/artifactory/tika
  - name: collabora
    url: https://collaboraonline.github.io/online/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: onlyoffice
    url: https://download.onlyoffice.com/charts/stable
  - name: postgres-operator
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator

releases:
  - name: tika
    namespace: tika
    chart: tika/tika
    version: 2.9.0
    values:
      - image:
          tag: "latest-full" # using "full" tag for OCR func.

  - name: collabora
    namespace: collabora
    chart: collabora/collabora-online
    version: 1.1.19
    values:
      - collabora:
          aliasgroups:
            - host: "collabora.case0sh.com" # needed because we connect via the ingress to the collaboration service
            # - host: "collaboration-collabora.ocis.svc.cluster.local" # needed if we would use the cluster internal Service to connect to the collaboration service
          extra_params: --o:ssl.enable=false --o:ssl.termination=true --o:net.frame_ancestors=ocis.kube.owncloud.test
      - ingress:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          hosts:
            - host: collabora.kube.owncloud.test
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: collabora-dev-tls
              hosts:
                - collabora.case0sh.com

  - name: ocis
    chart: ../../charts/ocis
    namespace: cloud
    values:
      - externalDomain: ocis.case0sh.com
      - ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          tls:
            - secretName: ocis-dev-tls
              hosts:
                - ocis.case0sh.com

      - insecure:
          oidcIdpInsecure: true
          ocisHttpApiInsecure: true

      - features:
          appsIntegration:
            enabled: true
            wopiIntegration:
              officeSuites:
                - name: Collabora
                  enabled: true
                  uri: "https://collabora.case0sh.com"
                  insecure: true
                  iconURI: https://collabora.case0sh.com/favicon.ico
                  ingress:
                    # Collabora connects to the collaboration service via Ingress in this case
                    enabled: true
                    domain: wopi-collabora.case0sh.com
                    ingressClassName: nginx
                    annotations:
                      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
                    tls:
                      - secretName: ocis-dev-tls
                        hosts:
                          - wopi-collabora.case0sh.com
                - name: OnlyOffice
                  enabled: false
                  uri: "https://onlyoffice.kube.owncloud.test"
                  insecure: true
                  iconURI: https://onlyoffice.kube.owncloud.test/web-apps/apps/documenteditor/main/resources/img/favicon.ico
                  ingress:
                    # OnlyOffice connects to the collaboration service via the cluster internal Service in this case
                    # We need to configure the internal hostname in the OnlyOffice ipfilter, see also:
                    # https://test-helpcenter.onlyoffice.com/installation/docs-configure-ipfilter.aspx
                    # we do this for this setup in deployments/ocis-office/addons/onlyoffice/configmap.yaml
                    enabled: false
            mimetypes:
              # mimetypes for creation
              - mime_type: application/vnd.oasis.opendocument.text
                extension: odt
                name: OpenDocument
                description: OpenDocument text document
                icon: image-edit
                default_app: "Collabora"
                allow_creation: true
              - mime_type: application/vnd.oasis.opendocument.spreadsheet
                extension: ods
                name: OpenSpreadsheet
                description: OpenDocument spreadsheet document
                icon: image-edit
                default_app: "Collabora"
                allow_creation: true
              - mime_type: application/vnd.oasis.opendocument.presentation
                extension: odp
                name: OpenPresentation
                description: OpenDocument presentation document
                icon: image-edit
                default_app: "Collabora"
                allow_creation: true
              - mime_type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
                extension: docx
                name: Text document
                description: Text document
                icon: image-edit
                default_app: "OnlyOffice"
                allow_creation: true
              - mime_type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                extension: xlsx
                name: Spreadsheet
                description: Spreadsheet
                icon: image-edit
                default_app: "OnlyOffice"
                allow_creation: true
              - mime_type: application/vnd.openxmlformats-officedocument.presentationml.presentation
                extension: pptx
                name: Presentation
                description: Presentation
                icon: image-edit
                default_app: "OnlyOffice"
                allow_creation: true
              - mime_type: application/vnd.openxmlformats-officedocument.wordprocessingml.form
                extension: docxf
                name: FormDocument
                description: Form document
                icon: image-edit
                default_app: "OnlyOffice"
                allow_creation: true

      - services:
          idm:
            persistence:
              enabled: true

          nats:
            persistence:
              enabled: true

          search:
            persistence:
              enabled: true
            extractor:
              type: tika
              tika:
                url: http://tika.tika.svc.cluster.local:9998

          storagesystem:
            persistence:
              enabled: true

          storageusers:
            persistence:
              enabled: true

          thumbnails:
            persistence:
              enabled: true

          web:
            persistence:
              enabled: true
