apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 1 #TODO: https://github.com/owncloud/ocis-charts/issues/12
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nats
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      {{- if and $.Values.services.nats.persistence.enabled $.Values.services.nats.persistence.chownInitContainer }}
      initContainers:
        - name: init-chown-data
          image: busybox
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }}", "/var/lib/ocis"]
          volumeMounts:
          - name: nats-data
            mountPath: /var/lib/ocis
      {{ end }}
      containers:
        - name: nats
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["nats", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            {{ if .Values.goMemLimit }}
            - name: GOMEMLIMIT
              value: {{ .Values.goMemLimit }}
            {{ end }}

            - name: NATS_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: NATS_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: NATS_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: NATS_TLS_SKIP_VERIFY_CLIENT_CERT
              value: "true"

            - name: NATS_NATS_HOST
              value: "0.0.0.0"
            - name: NATS_NATS_PORT
              value: "9233"
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: nats
              containerPort: 9233
          volumeMounts:
            - name: nats-data
              mountPath: /var/lib/ocis
      volumes:
      {{- if .Values.services.nats.persistence.enabled }}
        - name: nats-data
          persistentVolumeClaim:
            claimName: nats-data
      {{ else }}
        - name: nats-data
          emptyDir: {}
      {{ end }}
