apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: nats
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: nats
  ports:
    - name: nats
      port: 9233
      protocol: TCP
