apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: frontend
  {{- if and (not .Values.autoscaling.enabled) (.Values.services.frontend.replicas) }}
  replicas: {{ .Values.services.frontend.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: frontend
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: frontend
      containers:
        - name: frontend
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["frontend", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: FRONTEND_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: FRONTEND_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: FRONTEND_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: FRONTEND_HTTP_ADDR
              value: 0.0.0.0:9140
            - name: FRONTEND_PUBLIC_URL
              value: "https://{{ .Values.externalDomain }}"

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: FRONTEND_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            - name: FRONTEND_APP_HANDLER_INSECURE
              value: "{{ .Values.insecure.ocisHttpApiInsecure }}"

            - name: FRONTEND_ARCHIVER_INSECURE
              value: "{{ .Values.insecure.ocisHttpApiInsecure }}"

            - name: FRONTEND_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef }}
                  key: machine-auth-api-key

            - name: STORAGE_TRANSFER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.transferSecretSecretRef }}
                  key: transfer-secret

          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://localhost:9141/healthz
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
          - name: http
            containerPort: 9140
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
