apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: frontend
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 9140
      protocol: TCP
    - name: metrics-debug
      port: 9141
      protocol: TCP
