apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-bearer
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: auth-bearer
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: auth-bearer
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: auth-bearer
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["auth-bearer", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: AUTH_BEARER_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: AUTH_BEARER_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: AUTH_BEARER_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: AUTH_BEARER_OIDC_INSECURE
              value: "{{ .Values.insecure.oidcIdpInsecure }}"

            - name: AUTH_BEARER_GRPC_ADDR
              value: 0.0.0.0:9148

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: AUTH_BEARER_OIDC_ISSUER
            {{ if not .Values.features.externalUserManagement.enabled }}
              value: https://{{ .Values.externalDomain }}
            {{ else }}
              value: {{ .Values.features.externalUserManagement.oidc.issuerURI }}
            {{ end }}

            - name: AUTH_BEARER_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://localhost:9149/healthz
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9148
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
