{{- if not .Values.features.externalUserManagement.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
  annotations:
    ignore-check.kube-linter.io/env-var-secret : "IDP_ENCRYPTION_SECRET_FILE is no secret, it's the file path to the secret"
spec:
  selector:
    matchLabels:
      app: idp
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: idp
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: idp
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["idp", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            {{ if .Values.goMemLimit }}
            - name: GOMEMLIMIT
              value: {{ .Values.goMemLimit }}
            {{ end }}

            - name: MICRO_REGISTRY
              value: kubernetes

            - name: IDP_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: IDP_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: IDP_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: IDP_HTTP_ADDR
              value: 0.0.0.0:9130

            - name: IDP_ISS
              value: "https://{{ .Values.externalDomain }}"

            - name: IDP_LDAP_URI
              value: ldaps://idm:9235

            - name: IDP_LDAP_TLS_CACERT
              value: /etc/ocis/ldap-ca/ldap-ca.crt

            - name: IDP_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: idp-ldap-bind-password

            - name: IDP_SIGNING_PRIVATE_KEY_FILES
              value: /etc/ocis/idp/private-key.pem

            - name: IDP_ENCRYPTION_SECRET_FILE
              value: /etc/ocis/idp/encryption.key

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9130
          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
            - name: idp-secrets
              mountPath: /etc/ocis/idp
              readOnly: true
            - name: ocis-data-tmp
              mountPath: /var/lib/ocis # we mount that volume to apply fsGroup to that path, so that the idp can write the temporary idp/tmp/identifier-registration.yaml file
      volumes:
        - name: ocis-config-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
        - name: ldap-ca
          secret:
            secretName: {{ .Values.secretRefs.ldapCaRef }}
        - name: idp-secrets
          secret:
            secretName: {{ .Values.secretRefs.idpSecretRef }}
        - name: ocis-data-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
{{- end }}
