{{ if and (not .Values.features.externalUserManagement.enabled) (not .Values.secretRefs.idpSecretRef) }}
{{- $params := (dict)}}
{{- $_ := set $params "encryption.key" (randAscii 32) }}
{{- $_ := set $params "private-key.pem" (genPrivateKey "rsa") }}
{{- include "ocis.secret" (dict "scope" . "name" (include "secrets.idpSecret" .) "labels" .Values.backup.secretLabels "params" $params)}}
{{- end }}
---
{{ if and (not .Values.features.externalUserManagement.enabled) (not .Values.secretRefs.adminUserSecretRef) }}
{{- $params := (dict)}}
{{- $_ := set $params "user-id" uuidv4 }}
{{- $_ := set $params "password" (randAlphaNum 30) }}
{{- include "ocis.secret" (dict "scope" . "name" (include "secrets.adminUser" .) "params" $params)}}
{{- end }}
