{{- if not .Values.features.externalUserManagement.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: idp
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: idp
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: idp
  ports:
  - name: http
    port: 9130
    protocol: TCP
{{- end }}
