{{ if .Values.features.appsIntegration.enabled }}
{{- range $officeSuite := .Values.features.appsIntegration.wopiIntegration.officeSuites }}
{{ if $officeSuite.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-provider-{{ regexReplaceAll "\\W+" (lower $officeSuite.name) "_" }}
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app:  app-provider-{{ regexReplaceAll "\\W+" (lower $officeSuite.name) "_" }}
  replicas: 1 #TODO: https://github.com/owncloud/ocis-charts/issues/48
  {{- if $.Values.deploymentStrategy }}
  strategy: {{ toYaml $.Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app:  app-provider-{{ regexReplaceAll "\\W+" (lower $officeSuite.name) "_" }}
        {{- include "ocis.labels" $ | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ $.Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ $.Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name:  app-provider-{{ regexReplaceAll "\\W+" (lower $officeSuite.name) "_" }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["app-provider", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ $.Values.securityContext.runAsUser }}
            runAsGroup: {{ $.Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: APP_PROVIDER_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: APP_PROVIDER_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: APP_PROVIDER_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            # debug
            - name: APP_PROVIDER_DEBUG_PPROF
              value: "{{ $.Values.debug.profiling }}"

            - name: APP_PROVIDER_GRPC_ADDR
              value: 0.0.0.0:9164
            - name: APP_PROVIDER_DEBUG_ADDR
              value: 0.0.0.0:9165

            - name: APP_PROVIDER_EXTERNAL_ADDR
              value: app-provider-{{ regexReplaceAll "\\W+" (lower $officeSuite.name) "_" }}:9164

            - name: APP_PROVIDER_DRIVER
              value: wopi
            - name: APP_PROVIDER_WOPI_APP_NAME
              value: {{ $officeSuite.name }}
            - name: APP_PROVIDER_WOPI_APP_ICON_URI
              value: {{ $officeSuite.iconURI }}
            - name: APP_PROVIDER_WOPI_APP_URL
              value: {{ $officeSuite.uri }}
            - name: APP_PROVIDER_WOPI_INSECURE
              value: "{{ $officeSuite.insecure }}"
            - name: APP_PROVIDER_WOPI_WOPI_SERVER_EXTERNAL_URL
              value: {{ $.Values.features.appsIntegration.wopiIntegration.wopiServerURI }}

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: APP_PROVIDER_WOPI_FOLDER_URL_BASE_URL
              value: https://{{ $.Values.externalDomain }}

            - name: APP_PROVIDER_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://frontend:9140/app/list | grep {{ $officeSuite.name }}
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3

          resources: {{ toYaml $.Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9164
            - name: metrics-debug
              containerPort: 9165
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
{{ end }}
{{ end }}
{{ end }}
