{{ if .Values.features.appsIntegration.enabled }}
{{- range $officeSuite := .Values.features.appsIntegration.wopiIntegration.officeSuites }}
{{ if $officeSuite.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: app-provider-{{ regexReplaceAll "\\W+" (lower $officeSuite.name) "_" }}
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    app: app-provider-{{ regexReplaceAll "\\W+" (lower $officeSuite.name) "_" }}
    {{- include "ocis.labels" $ | nindent 4 }}
spec:
  selector:
    app: app-provider-{{ regexReplaceAll "\\W+" (lower $officeSuite.name) "_" }}
  ports:
    - name: grpc
      port: 9164
      protocol: TCP
    - name: metrics-debug
      port: 9165
      protocol: TCP
{{ end }}
{{ end }}
{{ end }}
