{{- if not .Values.configRefs.graphConfigRef }}
{{- $params := (dict)}}
{{- $_ := set $params "application-id" (uuidv4) }}
{{- include "ocis.configMap" (dict "scope" . "name" (include "config.graph" .) "params" $params)}}
{{- end }}
