apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: graph
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: graph
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: graph
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["graph", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: GRAPH_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: GRAPH_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: GRAPH_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: GRAPH_HTTP_ADDR
              value: 0.0.0.0:9120

            - name: GRAPH_SPACES_WEBDAV_BASE
              value: "https://{{ .Values.externalDomain }}"

            {{- if .Values.features.externalUserManagement.enabled }}
            - name: LDAP_INSECURE
              value: "{{ .Values.features.externalUserManagement.ldap.insecure }}"

            - name: LDAP_USER_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.user.baseDN }}
            - name: LDAP_GROUP_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.group.baseDN }}

            - name: LDAP_USER_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.user.scope }}
            - name: LDAP_GROUP_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.group.scope }}

            - name: LDAP_USER_SUBSTRING_FILTER_TYPE
              value: {{ .Values.features.externalUserManagement.ldap.user.substringFilterType }}

            - name: LDAP_USER_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.user.filter }}
            - name: LDAP_GROUP_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.group.filter }}

            - name: LDAP_USER_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.user.objectClass }}
            - name: LDAP_GROUP_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.group.objectClass }}

            - name: LDAP_USER_SCHEMA_ID
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.id }}
            - name: LDAP_GROUP_SCHEMA_ID
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.id }}

            - name: LDAP_USER_SCHEMA_ID_IS_OCTETSTRING
              value: "{{ .Values.features.externalUserManagement.ldap.user.schema.idIsOctetString }}"
            - name: LDAP_GROUP_SCHEMA_ID_IS_OCTETSTRING
              value: "{{ .Values.features.externalUserManagement.ldap.group.schema.idIsOctetString }}"

            - name: LDAP_USER_SCHEMA_MAIL
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.mail }}
            - name: LDAP_GROUP_SCHEMA_MAIL
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.mail }}

            - name: LDAP_USER_SCHEMA_DISPLAYNAME
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.displayName }}
            - name: LDAP_GROUP_SCHEMA_DISPLAYNAME
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.displayName }}

            - name: LDAP_USER_SCHEMA_USERNAME
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.userName }}
            - name: LDAP_GROUP_SCHEMA_GROUPNAME
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.groupName }}

            - name: LDAP_GROUP_SCHEMA_MEMBER
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.member }}
            {{- end }}

            - name: LDAP_URI
            {{ if not .Values.features.externalUserManagement.enabled }}
              value: ldaps://idm:9235
            {{ else }}
              value: {{ .Values.features.externalUserManagement.ldap.uri }}
            {{ end }}
            - name: LDAP_CACERT
              {{ if or (not .Values.features.externalUserManagement.enabled) ( not .Values.features.externalUserManagement.ldap.certTrusted) }}
              value: /etc/ocis/ldap-ca/ldap-ca.crt
              {{ else }}
              value: "" # no cert needed
              {{ end }}

            {{ if .Values.features.externalUserManagement.enabled }}
            - name: LDAP_BIND_DN
              value: {{ .Values.features.externalUserManagement.ldap.bindDN }}
            {{ end }}

            - name: GRAPH_SPACES_MAX_QUOTA_PERSONAL
              value: "{{ .Values.features.quota.personalSpaces.maxQuota }}"

            - name: GRAPH_SPACES_MAX_QUOTA_PROJECT
              value: "{{ .Values.features.quota.projectSpaces.maxQuota }}"

            - name: LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: reva-ldap-bind-password

            - name: REVA_GATEWAY
              value: gateway:9142
            - name: GRAPH_EVENTS_ENDPOINT
              value: nats:9233

            - name: GRAPH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://localhost:9124/healthz
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9120
          {{ if not .Values.features.externalUserManagement.enabled }}
          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
          {{ end }}
      {{ if not .Values.features.externalUserManagement.enabled }}
      volumes:
        - name: ocis-config-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
        - name: ldap-ca
          secret:
            secretName: {{ .Values.secretRefs.ldapCaRef }}
      {{ end }}
