apiVersion: v1
kind: Service
metadata:
  name: graph
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: graph
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: graph
  ports:
    - name: http
      port: 9120
      protocol: TCP
    - name: metrics-debug
      port: 9124
      protocol: TCP
