apiVersion: apps/v1
kind: Deployment
metadata:
  name: postprocessing
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: postprocessing
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: postprocessing
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: postprocessing
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["postprocessing", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            {{ if .Values.goMemLimit }}
            - name: GOMEMLIMIT
              value: {{ .Values.goMemLimit }}
            {{ end }}

            - name: POSTPROCESSING_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: POSTPROCESSING_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: POSTPROCESSING_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: POSTPROCESSING_EVENTS_ENDPOINT
              value: nats:9233
            - name: POSTPROCESSING_EVENTS_TLS_INSECURE
              value: "true"
            - name: SEARCH_EVENTS_TLS_INSECURE
              value: "true"

            - name: POSTPROCESSING_VIRUSSCAN
              value: "{{ .Values.services.antivirus.enabled }}"

          resources: {{ toYaml .Values.resources | nindent 12 }}
