{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNamePostprocessing" "appNameSuffix" "") -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postprocessing-restart-finished
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.services.postprocessing.maintenance.restartPostprocessingFinished.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.services.postprocessing.maintenance.restartPostprocessingFinished.startingDeadlineSeconds }}
  suspend: {{ not .Values.services.postprocessing.maintenance.restartPostprocessingFinished.enabled }}
  jobTemplate:
    spec:
      parallelism: 1
      template:
        metadata:
          labels:
            app: postprocessing-restart-finished
            {{- include "ocis.labels" . | nindent 12 }}

        spec:
          restartPolicy: Never
          {{- include "ocis.hostAliases" $ | nindent 10 }}
          nodeSelector: {{ toYaml $.jobNodeSelector | nindent 12 }}
          containers:
            - name: postprocessing-restart-finished
              {{- include "ocis.jobContainerImageOcis" . | nindent 14 }}
              command: ["ocis"]
              args: ["postprocessing", "restart", "-s", "finished"]
              securityContext:
                runAsNonRoot: true
                runAsUser: {{ .Values.securityContext.runAsUser }}
                runAsGroup: {{ .Values.securityContext.runAsGroup }}
                readOnlyRootFilesystem: true
              env:
                {{- include "ocis.events" . | nindent 16 }}

                # logging
                - name: POSTPROCESSING_LOG_COLOR
                  value: {{ .Values.logging.color | quote }}
                - name: POSTPROCESSING_LOG_LEVEL
                  value: {{ .Values.logging.level | quote }}
                - name: POSTPROCESSING_LOG_PRETTY
                  value: {{ .Values.logging.pretty | quote }}

              resources: {{ toYaml .jobResources | nindent 16 }}

          {{- include "ocis.imagePullSecrets" $ | nindent 10 }}
{{- if .Values.features.virusscan.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postprocessing-restart-virusscan
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.services.postprocessing.maintenance.restartPostprocessingVirusscan.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.services.postprocessing.maintenance.restartPostprocessingVirusscan.startingDeadlineSeconds }}
  suspend: {{ not .Values.services.postprocessing.maintenance.restartPostprocessingVirusscan.enabled }}
  jobTemplate:
    spec:
      parallelism: 1
      template:
        metadata:
          labels:
            app: postprocessing-restart-virusscan
            {{- include "ocis.labels" . | nindent 12 }}

        spec:
          restartPolicy: Never
          {{- include "ocis.hostAliases" $ | nindent 10 }}
          nodeSelector: {{ toYaml $.jobNodeSelector | nindent 12 }}
          containers:
            - name: postprocessing-restart-virusscan
              {{- include "ocis.jobContainerImageOcis" . | nindent 14 }}
              command: ["ocis"]
              args: ["postprocessing", "restart", "-s", "virusscan"]
              securityContext:
                runAsNonRoot: true
                runAsUser: {{ .Values.securityContext.runAsUser }}
                runAsGroup: {{ .Values.securityContext.runAsGroup }}
                readOnlyRootFilesystem: true
              env:
                {{- include "ocis.events" . | nindent 16 }}

                # logging
                - name: POSTPROCESSING_LOG_COLOR
                  value: {{ .Values.logging.color | quote }}
                - name: POSTPROCESSING_LOG_LEVEL
                  value: {{ .Values.logging.level | quote }}
                - name: POSTPROCESSING_LOG_PRETTY
                  value: {{ .Values.logging.pretty | quote }}

              resources: {{ toYaml .jobResources | nindent 16 }}

          {{- include "ocis.imagePullSecrets" $ | nindent 10 }}
{{ end }}
