releases:
  - name: ocis
    chart: ../../charts/ocis
    namespace: ocis
    values:
      - externalDomain: ocis.devdanylo.owncloud.works
      - deploymentStrategy:
          type: Recreate
      - ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          tls:
            - secretName: ocis-dev-tls
              hosts:
                - ocis.devdanylo.owncloud.works

      - logging:
          level: debug

      - insecure:
          oidcIdpInsecure: true
          ocisHttpApiInsecure: true

      - services:
          idm:
            persistence:
              enabled: true
              chownInitContainer: true

          nats:
            persistence:
              enabled: true
              chownInitContainer: true

          search:
            persistence:
              enabled: true
              chownInitContainer: true

          storagesystem:
            persistence:
              enabled: true
              chownInitContainer: true

          storageusers:
            persistence:
              enabled: true
              chownInitContainer: true

          store:
            persistence:
              enabled: true
              chownInitContainer: true

          thumbnails:

            persistence:
              enabled: true
              chownInitContainer: true

          web:
            persistence:
              enabled: true
              chownInitContainer: true
