releases:
  - name: custom-priorityclasses
    chart: ./examples

  - name: ocis
    chart: ../../charts/ocis
    namespace: ocis
    values:
      - externalDomain: ocis.kube.owncloud.test
      - priorityClassName: ocis-high-priority
      - ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          tls:
            - secretName: ocis-dev-tls
              hosts:
                - ocis.kube.owncloud.test
      - logging:
          level: debug

      - insecure:
          oidcIdpInsecure: true
          ocisHttpApiInsecure: true

      - services:
          idm:
            persistence:
              enabled: true

          appprovider:
            priorityClassName: ocis-low-priority

          notifications:
            priorityClassName: ocis-low-priority

          webdav:
            priorityClassName: ocis-medium-priority

          nats:
            persistence:
              enabled: true

          search:
            persistence:
              enabled: true
            priorityClassName: ocis-medium-priority

          storagesystem:
            persistence:
              enabled: true

          storageusers:
            persistence:
              enabled: true
            priorityClassName: ocis-high-priority
            jobPriorityClassName: ocis-low-priority

          thumbnails:
            persistence:
              enabled: true
            priorityClassName: ocis-low-priority
            jobPriorityClassName: ocis-low-priority

          web:
            persistence:
              enabled: true
            priorityClassName: ocis-high-priority
