{{- if or (not .Values.secretRefs.collaborationJwtSecretRef) }}
{{- $params := (dict)}}
{{- $_ := set $params "jwt-secret" (randAlphaNum 30) }}
{{- include "ocis.secret" (dict "scope" . "name" "collaboration-jwt-secret" "params" $params)}}
{{- end }}
---
{{- if or (not .Values.secretRefs.collaborationWopiSecret) }}
{{- $params := (dict)}}
{{- $_ := set $params "wopi-secret" (randAlphaNum 30) }}
{{- include "ocis.secret" (dict "scope" . "name" "collaboration-wopi-secret" "params" $params)}}
{{- end }}
