{{ if .Values.features.ocm.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameOcm" "appNameSuffix" "") -}}
{{- $_ := set . "autoscaling" (default (default (dict) .Values.autoscaling) .Values.services.sse.autoscaling) -}}
{{ include "ocis.hpa" . }}
{{ end }}
