---
apiVersion: jetstream.nats.io/v1beta2
kind: Account
metadata:
  name: ocis-nats
spec:
  name: ocis-nats
  servers:
    - nats://nats.ocis-nats.svc.cluster.local:4222

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: main-queue
spec:
  account: ocis-nats
  allowRollup: false
  description: oCIS message bus
  discard: old
  duplicateWindow: "2m0s"
  maxAge: "168h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 0
  name: main-queue
  noAck: false
  #maxAckPending: #TODO: acts as default for SSE and undefined clients??
  #maxWaiting:
  #ackWait:
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: file
  subjects:
    - main-queue

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-cache-userinfo
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS proxy userinfo cache
  denyDelete: true
  discard: new
  duplicateWindow: "10s"
  maxAge: "10s"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_cache-userinfo
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.cache-userinfo.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-userlog
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS userlog store
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "336h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_userlog
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: file
  subjects:
    - $KV.userlog.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-activitylog
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS activitylog store
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "336h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_activitylog
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: file
  subjects:
    - $KV.activitylog.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-postprocessing
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS postprocessing store
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "168h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_postprocessing
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: file
  subjects:
    - $KV.postprocessing.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-ids-storage-users
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS storageusers id cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_ids-storage-users
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.ids-storage-users.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-storage-users
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS storageusers cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_storage-users
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.storage-users.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-eventhistory
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS userlog store
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "336h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_eventhistory
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: file
  subjects:
    - $KV.eventhistory.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-service-registry
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS service registry
  denyDelete: true
  discard: new
  duplicateWindow: "30s"
  maxAge: "30s"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_service-registry
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.service-registry.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-settings-cache
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS settings cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "10m0s"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_settings-cache
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.settings-cache.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-storage-system
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS storagesystem cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_storage-system
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.storage-system.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-cache-roles
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS graph roles cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_cache-roles
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.cache-roles.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-proxy
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS ocs and proxy signing keys
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_proxy
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.proxy.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-ocis-pkg
spec:
  account: ocis-nats
  allowRollup: true
  description: oCIS settings roles cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_ocis-pkg
  noAck: false
  allowDirect: false # differs from the oCIS product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.ocis-pkg.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: activitylog
spec:
  streamName: main-queue
  durableName: activitylog
  deliverGroup: activitylog
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: antivirus
spec:
  streamName: main-queue
  durableName: antivirus
  deliverGroup: antivirus
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: audit
spec:
  streamName: main-queue
  durableName: audit
  deliverGroup: audit
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: clientlog
spec:
  streamName: main-queue
  durableName: clientlog
  deliverGroup: clientlog
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: dcfs
spec:
  streamName: main-queue
  durableName: dcfs
  deliverGroup: dcfs
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: evhistory
spec:
  streamName: main-queue
  durableName: evhistory
  deliverGroup: evhistory
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: frontend
spec:
  streamName: main-queue
  durableName: frontend
  deliverGroup: frontend
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: graph
spec:
  streamName: main-queue
  durableName: graph
  deliverGroup: graph
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: notifications
spec:
  streamName: main-queue
  durableName: notifications
  deliverGroup: notifications
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: policies
spec:
  streamName: main-queue
  durableName: policies
  deliverGroup: policies
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0


---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: postprocessing
spec:
  streamName: main-queue
  durableName: postprocessing
  deliverGroup: postprocessing
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: search
spec:
  streamName: main-queue
  durableName: search
  deliverGroup: search
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: storage-users
spec:
  streamName: main-queue
  durableName: storage-users
  deliverGroup: storage-users
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0

---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: userlog
spec:
  streamName: main-queue
  durableName: userlog
  deliverGroup: userlog
  deliverPolicy: new
  filterSubject: main-queue
  ackPolicy: explicit
  ackWait: 30s
  maxAckPending: 1000
  maxDeliver: -1
  replayPolicy: instant
  numReplicas: 0
