---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: main-queue
spec:
  name: main-queue
  replicas: 3
  storage: file
  retention: limits
  discard: old
  duplicateWindow: "2m0s"
  account: ocis-nats
---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: eventhistory
spec:
  name: OBJ_eventhistory
  subjects:
    - $O.eventhistory.C.>
    - $O.eventhistory.M.>
  replicas: 3
  storage: file
  retention: limits
  discard: old
  duplicateWindow: "2m0s"
  maxAge: "336h"
  allowRollup: true
  allowDirect: true
  account: ocis-nats
---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: userlog
spec:
  name: OBJ_userlog
  subjects:
    - $O.userlog.C.>
    - $O.userlog.M.>
  replicas: 3
  storage: file
  retention: limits
  discard: old
  duplicateWindow: "2m0s"
  allowRollup: true
  allowDirect: true
  maxAge: "336h"
  account: ocis-nats
---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: postprocessing
spec:
  name: OBJ_postprocessing
  subjects:
    - $O.postprocessing.C.>
    - $O.postprocessing.M.>
  replicas: 3
  storage: file
  retention: limits
  discard: old
  duplicateWindow: "2m0s"
  allowRollup: true
  allowDirect: true
  account: ocis-nats
---
apiVersion: jetstream.nats.io/v1beta2
kind: Account
metadata:
  name: ocis-nats
spec:
  name: ocis-nats
  servers:
  - nats://nats.ocis-nats.svc.cluster.local:4222
