apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "postgres"
spec:
  teamId: "postgres"
  volume:
    size: "10Gi"
  numberOfInstances: 3
  users:
    "onlyoffice":
      - superuser
      - createdb
  databases:
    "onlyoffice": "onlyoffice"
  postgresql:
    version: "15"
    parameters:
      max_connections: "330"
  enableConnectionPooler: true
