{{ if not .Values.secretRefs.storagesystemJwtSecretRef }}
{{- $params := (dict)}}
{{- $_ := set $params "storage-system-jwt-secret" (randAlphaNum 30) }}
{{- include "ocis.secret" (dict "scope" . "name" (include "secrets.storageSystemJWTSecret" .) "params" $params)}}
{{- end }}
---
{{ if not .Values.secretRefs.storagesystemSecretRef }}
{{- $params := (dict)}}
{{- $_ := set $params "api-key" (randAlphaNum 30) }}
{{- $_ := set $params "user-id" uuidv4 }}
{{- include "ocis.secret" (dict "scope" . "name"  (include "secrets.storageSystemSecret" .) "labels" .Values.backup.secretLabels "params" $params)}}
{{- end }}
---
{{ if not .Values.secretRefs.transferSecretSecretRef }}
{{- $params := (dict)}}
{{- $_ := set $params "transfer-secret" (randAlphaNum 30) }}
{{- include "ocis.secret" (dict "scope" . "name"  (include "secrets.transferSecret" .) "params" $params)}}
{{- end }}
