{{- if .Values.features.emailNotifications.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: notifications
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: notifications
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: notifications
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["notifications", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: NOTIFICATIONS_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: NOTIFICATIONS_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: NOTIFICATIONS_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: NOTIFICATIONS_SMTP_HOST
              value: "{{ .Values.features.emailNotifications.smtp.host }}"
            - name: NOTIFICATIONS_SMTP_PORT
              value: "{{ .Values.features.emailNotifications.smtp.port }}"
            - name: NOTIFICATIONS_SMTP_SENDER
              value: "{{ .Values.features.emailNotifications.smtp.sender }}"
            - name: NOTIFICATIONS_SMTP_AUTHENTICATION
              value: "{{ .Values.features.emailNotifications.smtp.authentication }}"
            - name: NOTIFICATIONS_SMTP_ENCRYPTION
              value: "{{ .Values.features.emailNotifications.smtp.encryption }}"

            - name: NOTIFICATIONS_SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.notificationsSmtpSecretRef }}
                  key: smtp-username

            - name: NOTIFICATIONS_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.notificationsSmtpSecretRef }}
                  key: smtp-password

            - name: REVA_GATEWAY
              value: gateway:9142
            - name: NOTIFICATIONS_EVENTS_ENDPOINT
              value: nats:9233
            - name: NOTIFICATIONS_EVENTS_TLS_INSECURE
              value: "true"

            - name: OCIS_URL
              value: https://{{ .Values.externalDomain }}

            - name: OCIS_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef }}
                  key: machine-auth-api-key

            - name: NOTIFICATIONS_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef }}
                  key: machine-auth-api-key

          resources: {{ toYaml .Values.resources | nindent 12 }}
{{- end }}
