{{- if not .Values.secretRefs.thumbnailsSecretRef }}
{{- $params := (dict)}}
{{- $_ := set $params "thumbnails-transfer-secret" (randAlphaNum 30) }}
{{- include "ocis.secret" (dict "scope" . "name" (include "secrets.thumbnailsSecret" .) "params" $params)}}
{{- end }}
