{{- if not .Values.configRefs.authServiceConfigRef }}
{{- $params := (dict)}}
{{- $_ := set $params "service-account-id" (uuidv4) }}
{{- include "ocis.configMap" (dict "scope" . "name" (include "config.authService" .) "params" $params)}}
{{- end }}
