{{- if or (not .Values.secretRefs.serviceAccountSecretRef) }}
{{- $params := (dict)}}
{{- $_ := set $params "service-account-secret" (randAlphaNum 30) }}
{{- include "ocis.secret" (dict "scope" . "name" (include "secrets.serviceAccountSecret" .) "params" $params)}}
{{- end }}
