apiVersion: apps/v1
kind: Deployment
metadata:
  name: experimental
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: experimental
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: experimental
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: experimental
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["experimental", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: EXPERIMENTAL_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: EXPERIMENTAL_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: EXPERIMENTAL_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: EXPERIMENTAL_HTTP_ADDR
              value: 0.0.0.0:9180

            - name: EXPERIMENTAL_EVENTS_ENDPOINT
              value: nats:9233
            - name: EXPERIMENTAL_EVENTS_TLS_INSECURE
              value: "true"
            - name: SEARCH_EVENTS_TLS_INSECURE
              value: "true"

            - name: OCIS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9180
