{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameProxy" "appNameSuffix" "") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .appName }}-config
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
data:
  proxy.yaml: |
    ---
    policy_selector:
      static:
        policy: ocis
    {{- with $.Values.features.quotas.roles }}
    role_quotas:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $.Values.features.externalUserManagement.oidc.roleAssignment.enabled }}
    role_assignment:
      driver: oidc
      {{- if or $.Values.features.externalUserManagement.oidc.roleAssignment.claim $.Values.features.externalUserManagement.oidc.roleAssignment.mapping }}
      oidc_role_mapper:
        {{- with $.Values.features.externalUserManagement.oidc.roleAssignment.claim }}
        role_claim: {{ . }}
        {{- end }}
        {{- with $.Values.features.externalUserManagement.oidc.roleAssignment.mapping }}
        role_mapping:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
  csp.yaml: |
    directives:
      child-src:
        - '''self'''
      connect-src:
        - '''self'''
      default-src:
        - '''none'''
      font-src:
        - '''self'''
      frame-ancestors:
        - '''self'''
      frame-src:
        - '''self'''
        - 'https://embed.diagrams.net/'
        - 'https://collabora.kube.owncloud.test/'
        - 'https://onlyoffice.kube.owncloud.test/'
      img-src:
        - '''self'''
        - 'data:'
        - 'blob:'
        - 'https://collabora.kube.owncloud.test/'
        - 'https://onlyoffice.kube.owncloud.test/'
      manifest-src:
        - '''self'''
      media-src:
        - '''self'''
      object-src:
        - '''self'''
        - 'blob:'
      script-src:
        - '''self'''
        - '''unsafe-inline'''
      style-src:
        - '''self'''
        - '''unsafe-inline'''
