apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
data:
  proxy.yaml: |
    ---
    policy_selector:
      static:
        policy: ocis
    policies:
    - name: ocis
      routes:
      - endpoint: /
        backend: http://web:9100
      - endpoint: /.well-known/
        backend: http://idp:9130
      - endpoint: /konnect/
        backend: http://idp:9130
      - endpoint: /signin/
        backend: http://idp:9130
      - endpoint: /archiver
        backend: http://frontend:9140
      - type: regex
        endpoint: /ocs/v[12].php/cloud/user/signing-key
        backend: http://ocs:9110
      - endpoint: /ocs/
        backend: http://frontend:9140
      - type: query
        endpoint: /remote.php/?preview=1
        backend: http://webdav:9115
      - method: REPORT
        endpoint: /remote.php/dav/
        backend: http://webdav:9115
      - type: query
        endpoint: /dav/?preview=1
        backend: http://webdav:9115
      - type: query
        endpoint: /webdav/?preview=1
        backend: http://webdav:9115
      - endpoint: /remote.php/
        backend: http://ocdav:8080 # TODO: investigate why service discovery did not work here, 502 bad gateway
      - endpoint: /dav/
        backend: http://ocdav:8080
      - endpoint: /webdav/
        backend: http://ocdav:8080
      - endpoint: /status.php
        backend: http://ocdav:8080
      - endpoint: /index.php/
        backend: http://ocdav:8080
      - endpoint: /apps/
        backend: http://ocdav:8080
      - endpoint: /data
        backend: http://frontend:9140
      - endpoint: /app/
        backend: http://frontend:9140
      - endpoint: /graph/
        backend: http://graph:9120
      - endpoint: /graph-explorer
        backend: http://graph-explorer:9135
      - endpoint: /experimental
        backend: http://experimental:9180
      - endpoint: /api/v0/settings
        backend: http://settings:9190
      - endpoint: /settings.js
        backend: http://settings:9190
