---
{{ if not .Values.secretRefs.jwtSecretRef }}
{{- $params := (dict)}}
{{- $_ := set $params "jwt-secret" (randAlphaNum 30) }}
{{- include "ocis.secret" (dict "scope" . "name" (include "secrets.jwtSecret" .) "params" $params)}}
{{- end }}
