apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: users
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: users
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: users
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["users", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            {{ if .Values.goMemLimit }}
            - name: GOMEMLIMIT
              value: {{ .Values.goMemLimit }}
            {{ end }}

            - name: MICRO_REGISTRY
              value: kubernetes

            - name: USERS_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: USERS_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: USERS_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            # debug
            - name: USERS_DEBUG_PPROF
              value: "{{ .Values.debug.profiling }}"

            - name: USERS_GRPC_ADDR
              value: 0.0.0.0:9144
            - name: USERS_DEBUG_ADDR
              value: 0.0.0.0:9145

            {{- if .Values.features.externalUserManagement.enabled }}
            - name: USERS_LDAP_INSECURE
              value: "{{ .Values.features.externalUserManagement.ldap.insecure }}"

            - name: USERS_LDAP_USER_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.user.baseDN }}
            - name: USERS_LDAP_GROUP_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.group.baseDN }}

            - name: USERS_LDAP_USER_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.user.scope }}
            - name: USERS_LDAP_GROUP_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.group.scope }}

            - name: USERS_LDAP_USER_SUBSTRING_FILTER_TYPE
              value: {{ .Values.features.externalUserManagement.ldap.user.substringFilterType }}

            - name: USERS_LDAP_USER_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.user.filter }}
            - name: USERS_LDAP_GROUP_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.group.filter }}

            - name: USERS_LDAP_USER_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.user.objectClass }}
            - name: USERS_LDAP_GROUP_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.group.objectClass }}

            - name: USERS_LDAP_USER_SCHEMA_ID
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.id }}
            - name: USERS_LDAP_GROUP_SCHEMA_ID
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.id }}

            - name: USERS_LDAP_USER_SCHEMA_ID_IS_OCTETSTRING
              value: "{{ .Values.features.externalUserManagement.ldap.user.schema.idIsOctetString }}"
            - name: USERS_LDAP_GROUP_SCHEMA_ID_IS_OCTETSTRING
              value: "{{ .Values.features.externalUserManagement.ldap.group.schema.idIsOctetString }}"

            - name: USERS_LDAP_USER_SCHEMA_MAIL
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.mail }}
            - name: USERS_LDAP_GROUP_SCHEMA_MAIL
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.mail }}

            - name: USERS_LDAP_USER_SCHEMA_DISPLAYNAME
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.displayName }}
            - name: USERS_LDAP_GROUP_SCHEMA_DISPLAYNAME
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.displayName }}

            - name: USERS_LDAP_USER_SCHEMA_USERNAME
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.userName }}
            - name: USERS_LDAP_GROUP_SCHEMA_GROUPNAME
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.groupName }}

            - name: USERS_LDAP_GROUP_SCHEMA_MEMBER
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.member }}
            {{- end }}

            - name: USERS_LDAP_URI
            {{ if not .Values.features.externalUserManagement.enabled }}
              value: ldaps://idm:9235
            {{ else }}
              value: {{ .Values.features.externalUserManagement.ldap.uri }}
            {{ end }}

            - name: USERS_LDAP_CACERT
              {{ if or (not .Values.features.externalUserManagement.enabled) (not .Values.features.externalUserManagement.ldap.certTrusted) }}
              value: /etc/ocis/ldap-ca/ldap-ca.crt
              {{ else }}
              value: "" # no cert needed
              {{ end }}

            {{ if .Values.features.externalUserManagement.enabled }}
            - name: USERS_LDAP_BIND_DN
              value: {{ .Values.features.externalUserManagement.ldap.bindDN }}
            {{ end }}

            - name: USERS_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: reva-ldap-bind-password
            - name: USERS_IDP_URL
            {{ if not .Values.features.externalUserManagement.enabled }}
              value: https://{{ .Values.externalDomain }}
            {{ else }}
              value: {{ .Values.features.externalUserManagement.oidc.issuerURI }}
            {{ end }}

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: USERS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://localhost:9145/healthz
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3


          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9144
            - name: metrics-debug
              containerPort: 9145
          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            {{ if or (not .Values.features.externalUserManagement.enabled) ( not .Values.features.externalUserManagement.ldap.certTrusted) }}
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
            {{ end }}
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: ocis-config-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
        {{ if or (not .Values.features.externalUserManagement.enabled) ( not .Values.features.externalUserManagement.ldap.certTrusted) }}
        - name: ldap-ca
          secret:
            secretName: {{ .Values.secretRefs.ldapCaRef }}
        {{ end }}
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
