apiVersion: v1
kind: Service
metadata:
  name: antivirus
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: antivirus
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: antivirus
  ports:
    - name: metrics-debug
      port: 9205
      protocol: TCP
