apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-users
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: storage-users
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: storage-users
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      {{- if and $.Values.services.storageUsers.persistence.enabled $.Values.services.storageUsers.persistence.chownInitContainer }}
      initContainers:
        - name: init-chown-data
          image: busybox
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }}", "/var/lib/ocis"]
          volumeMounts:
          - name: storage-users-data
            mountPath: /var/lib/ocis
      {{ end }}
      containers:
        - name: storage-users
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["storage-users", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            # logging
            - name: STORAGE_USERS_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: STORAGE_USERS_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: STORAGE_USERS_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            # external availability grpc
            - name: STORAGE_USERS_GRPC_ADDR
              value: 0.0.0.0:9157

            - name: STORAGE_USERS_DEBUG_ADDR
              value: 0.0.0.0:9159

            # external availability data gateway
            - name: STORAGE_USERS_HTTP_ADDR
              value: 0.0.0.0:9158
            - name: STORAGE_USERS_DATA_SERVER_URL
              value: "http://storage-users:9158/data"
            - name: STORAGE_USERS_DATA_GATEWAY_URL
              value: "http://frontend:9140/data"

            - name: STORAGE_USERS_PERMISSION_ENDPOINT
              value: settings:9191

            - name: STORAGE_USERS_OCIS_ASYNC_UPLOADS
              value: "true"

            # oCIS storage driver (decomposed filesystem)
            {{- if  eq .Values.services.storageUsers.storageBackend.driver "ocis" }}
            - name: STORAGE_USERS_DRIVER
              value: ocis
            {{- end }}

            # S3ng storage driver (decomposed filesystem)
            {{- if  eq .Values.services.storageUsers.storageBackend.driver "s3ng" }}
            - name: STORAGE_USERS_DRIVER
              value: s3ng
            - name: STORAGE_USERS_S3NG_ENDPOINT
              value: "{{ .Values.services.storageUsers.storageBackend.driverConfig.s3ng.endpoint }}"
            - name: STORAGE_USERS_S3NG_REGION
              value: "{{ .Values.services.storageUsers.storageBackend.driverConfig.s3ng.region }}"
            - name: STORAGE_USERS_S3NG_ACCESS_KEY
              value: "{{ .Values.services.storageUsers.storageBackend.driverConfig.s3ng.accessKey }}"
            - name: STORAGE_USERS_S3NG_SECRET_KEY
              value: "{{ .Values.services.storageUsers.storageBackend.driverConfig.s3ng.secretKey }}"
            - name: STORAGE_USERS_S3NG_BUCKET
              value: "{{ .Values.services.storageUsers.storageBackend.driverConfig.s3ng.bucket }}"
            {{- end }}

            # cache
            - name: STORAGE_USERS_CACHE_STORE
              value: redis
            - name: STORAGE_USERS_CACHE_NODES
              value: redis-master.ocis-redis.svc.cluster.local:6379

            # events
            - name: STORAGE_USERS_EVENTS_ENDPOINT
              value: nats:9233
            - name: STORAGE_USERS_EVENTS_TLS_INSECURE
              value: "true"

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: STORAGE_USERS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            - name: STORAGE_TRANSFER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.transferSecretSecretRef }}
                  key: transfer-secret

          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://localhost:9159/healthz
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3


          resources: {{ toYaml .Values.services.storageUsers.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9157
            - name: http
              containerPort: 9158
            - name: metrics
              containerPort: 9159
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: storage-users-data
              mountPath: /var/lib/ocis
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
      {{- if .Values.services.storageUsers.persistence.enabled }}
        - name: storage-users-data
          persistentVolumeClaim:
            claimName: storage-users-data
      {{ else }}
        - name: storage-users-data
          emptyDir: {}
      {{ end }}
