apiVersion: v1
kind: Service
metadata:
  name: storage-users
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: storage-users
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: storage-users
  ports:
    - name: grpc
      port: 9157
      protocol: TCP
    - name: http
      port: 9158
      protocol: TCP
    - name: metrics-debug
      port: 9159
      protocol: TCP
