apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-system
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: storage-system
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: storage-system
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      {{- if and $.Values.services.storageSystem.persistence.enabled $.Values.services.storageSystem.persistence.chownInitContainer }}
      initContainers:
        - name: init-chown-data
          image: busybox
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }}", "/var/lib/ocis"]
          volumeMounts:
          - name: storage-system-data
            mountPath: /var/lib/ocis
      {{ end }}
      containers:
        - name: storage-system
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["storage-system", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            # logging
            - name: STORAGE_SYSTEM_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: STORAGE_SYSTEM_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: STORAGE_SYSTEM_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            # external availability grpc
            - name: STORAGE_SYSTEM_GRPC_ADDR
              value: 0.0.0.0:9215

            # external availability data gateway
            - name: STORAGE_SYSTEM_HTTP_ADDR
              value: 0.0.0.0:9216
            - name: STORAGE_SYSTEM_DATA_SERVER_URL
              value: http://storage-system:9216/data

            - name: REVA_GATEWAY
              value: "gateway:9142"

            - name: STORAGE_SYSTEM_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storageSystemJwtSecretRef }}
                  key: storage-system-jwt-secret

            - name: OCIS_SYSTEM_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storageSystemSecretRef }}
                  key: api-key

            - name: OCIS_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storageSystemSecretRef }}
                  key: user-id

          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://localhost:9217/healthz
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3


          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9215
            - name: http
              containerPort: 9216
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: storage-system-data
              mountPath: /var/lib/ocis
      volumes:
        - name: tmp-volume
          emptyDir:
              medium: Memory
              sizeLimit: 6Mi
      {{- if .Values.services.storageSystem.persistence.enabled }}
        - name: storage-system-data
          persistentVolumeClaim:
            claimName: storage-system-data
      {{ else }}
        - name: storage-system-data
          emptyDir: {}
      {{ end }}
