apiVersion: v1
kind: Service
metadata:
  name: storage-system
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: storage-system
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: storage-system
  ports:
    - name: grpc
      port: 9215
      protocol: TCP
    - name: http
      port: 9216
      protocol: TCP
    - name: metrics-debug
      port: 9217
      protocol: TCP
