apiVersion: v1
kind: Service
metadata:
  name: groups
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: groups
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: groups
  ports:
    - name: grpc
      port: 9160
      protocol: TCP
    - name: metrics-debug
      port: 9161
      protocol: TCP
