{{ if .Values.features.appsIntegration.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-registry
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: app-registry
  replicas: 1 #TODO: https://github.com/owncloud/ocis-charts/issues/48
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: app-registry
        {{- include "ocis.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/app-registry/config.yaml") . | sha256sum }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: app-registry
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["app-registry", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: APP_REGISTRY_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: APP_REGISTRY_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: APP_REGISTRY_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            # debug
            - name: APP_REGISTRY_DEBUG_PPROF
              value: "{{ .Values.debug.profiling }}"

            - name: APP_REGISTRY_GRPC_ADDR
              value: 0.0.0.0:9242
            - name: APP_REGISTRY_DEBUG_ADDR
              value: 0.0.0.0:9243

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: APP_REGISTRY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://localhost:9243/healthz
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9242
            - name: metrics-debug
              containerPort: 9243
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: configs
              mountPath: /etc/ocis
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
        - name: configs
          configMap:
            name: app-registry-config
{{ end }}
