{{ if .Values.features.appsIntegration.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: app-registry
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: app-registry
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: app-registry
  ports:
    - name: grpc
      port: 9242
      protocol: TCP
    - name: metrics-debug
      port: 9243
      protocol: TCP
{{ end }}
