apiVersion: v1
kind: Service
metadata:
  name: auth-machine
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: auth-machine
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: auth-machine
  ports:
    - name: grpc
      port: 9166
      protocol: TCP
