{{- if or (not .Values.secretRefs.machineAuthApiKeySecretRef) }}
{{- $params := (dict)}}
{{- $_ := set $params "machine-auth-api-key" (randAlphaNum 30) }}
{{- include "ocis.secret" (dict "scope" . "name" (include "secrets.machineAuthAPIKeySecret" .) "params" $params)}}
{{- end }}
