apiVersion: v1
kind: Service
metadata:
  name: auth-basic
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: auth-basic
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: auth-basic
  ports:
    - name: grpc
      port: 9146
      protocol: TCP
    - name: metrics-debug
      port: 9147
      protocol: TCP
