apiVersion: v1
kind: Service
metadata:
  name: webdav
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: webdav
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: webdav
  ports:
    - name: http
      port: 9115
      protocol: TCP
    - name: metrics-debug
      port: 9119
      protocol: TCP
