apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: web
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 9100
      protocol: TCP
    - name: metrics-debug
      port: 9104
      protocol: TCP
