apiVersion: v1
kind: Service
metadata:
  name: storage-shares
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: storage-shares
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: storage-shares
  ports:
    - name: grpc
      port: 9154
      protocol: TCP
    - name: metrics-debug
      port: 9156
      protocol: TCP
