apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-publiclink
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: storage-publiclink
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: storage-publiclink
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: storage-publiclink
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["storage-publiclink", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: STORAGE_PUBLICLINK_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: STORAGE_PUBLICLINK_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: STORAGE_PUBLICLINK_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            # debug
            - name: STORAGE_PUBLICLINK_DEBUG_PPROF
              value: "{{ .Values.debug.profiling }}"

            - name: STORAGE_PUBLICLINK_GRPC_ADDR
              value: 0.0.0.0:9178
            - name: STORAGE_PUBLICLINK_DEBUG_ADDR
              value: 0.0.0.0:9179

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: STORAGE_PUBLICLINK_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://localhost:9179/healthz
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9178
            - name: metrics-debug
              containerPort: 9179
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
