apiVersion: v1
kind: Service
metadata:
  name: storage-publiclink
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: storage-publiclink
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: storage-publiclink
  ports:
    - name: grpc
      port: 9178
      protocol: TCP
    - name: metrics-debug
      port: 9179
      protocol: TCP
