repositories:
  - name: inbucket
    url: https://inbucket.github.io/inbucket-community

releases:
  - name: inbucket
    chart: inbucket/inbucket
    namespace: inbucket
    values:
      - ingress:
          enabled: true
          hosts:
            - host: inbucket.kube.owncloud.test
              paths:
                - path: /
          tls:
            - secretName: inbucket-tls
              hosts:
                - inbucket.kube.owncloud.test

  - name: ocis
    chart: ../../charts/ocis
    namespace: ocis
    values:
      - image:
          repository: owncloud/ocis
          tag: dev
      - externalDomain: ocis.kube.owncloud.test
      - ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          tls:
            - secretName: ocis-dev-tls
              hosts:
                - ocis.kube.owncloud.test

      - logging: &logging
          level: debug

      - insecure: &insecure
          oidcIdpInsecure: true
          ocisHttpApiInsecure: true
          ocmInsecure: true

      - features: &features
          demoUsers: true
          emailNotifications: # OCM invitations may be sent via email
            enabled: true
            smtp:
              host: inbucket.inbucket.svc.cluster.local
              port: 2500
              sender: "ownCloud <noreply@ocis.kube.owncloud.test>"
              authentication: none
              encryption: none
          ocm:
            enabled: true
            providersConfigRef: "ocmproviders"

      - services: &services
          idm:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          nats:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          search:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          storagesystem:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          ocm:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          storageusers:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          thumbnails:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          web:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
            config:
              apps:
                - files
                - search
                - text-editor
                - pdf-viewer
                - external
                - admin-settings
                - epub-reader
                - preview
                - app-store
                - ocm

      - extraResources:
          - &ocmproviders |
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: ocmproviders
              namespace: {{ "{{" }} template "ocis.namespace" . {{ "}}" }}
              labels:
                {{ "{{" }}- include "ocis.labels" . | nindent 4 {{ "}}" }}
            data:
              ocmproviders.json: |
                [
                  {
                    "name": "ocis-server",
                    "full_name": "first-ocis-instance",
                    "organization": "Owncloud",
                    "domain": ".*.kube.owncloud.test",
                    "homepage": "https://owncloud.com",
                    "services": [
                      {
                        "endpoint": {
                          "type": {
                            "name": "OCM",
                            "description": "ocis.owncloud.test Open Cloud Mesh API"
                          },
                          "name": "ocis - OCM API",
                          "path": "https://.*.kube.owncloud.test/ocm/",
                          "is_monitored": true
                        },
                        "api_version": "0.0.1",
                        "host": ".*.kube.owncloud.test"
                      },
                      {
                        "endpoint": {
                          "type": {
                            "name": "Webdav",
                            "description": "ocis.owncloud.test Webdav API"
                          },
                          "name": "ocis - Webdav API",
                          "path": "https://.*.kube.owncloud.test/dav/",
                          "is_monitored": true
                        },
                        "api_version": "0.0.1",
                        "host": ".*.kube.owncloud.test"
                      }
                    ]
                  }
                ]

  - name: ocis2
    chart: ../../charts/ocis
    namespace: ocis2
    values:
      - image:
          repository: owncloud/ocis
          tag: dev
      - externalDomain: ocis2.kube.owncloud.test
      - ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          tls:
            - secretName: ocis-dev-tls
              hosts:
                - ocis2.kube.owncloud.test

      # for the following configuration, see the other oCIS release
      - logging:
          <<: *logging
      - insecure:
          <<: *insecure
      - features:
          <<: *features
      - services:
          <<: *services
      - extraResources:
          - *ocmproviders
