releases:
  - name: ocis
    chart: ../../charts/ocis
    namespace: ocis
    values:
      - externalDomain: ocis.kube.owncloud.test
      - ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          tls:
            - secretName: ocis-dev-tls
              hosts:
                - ocis.kube.owncloud.test

      - logging:
          level: debug

      - insecure:
          oidcIdpInsecure: true
          ocisHttpApiInsecure: true
          ocmInsecure: true

      - features:
          demoUsers: true
          ocm:
            enabled: true
            providersConfigRef: "ocmproviders"

      - services:
          idm:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          nats:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          search:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          storagesystem:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          storageusers:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
            maintenance:
              cleanUpExpiredUploads:
                enabled: true
                schedule: "* * * * *"
              purgeExpiredTrashBinItems:
                enabled: true
                schedule: "* * * * *"
              restartPostprocessing:
                enabled: true
                schedule: "* * * * *"

          thumbnails:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
            maintenance:
              cleanUpOldThumbnails:
                enabled: true
                schedule: "* * * * *"

          web:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
            config:
              apps:
                - files
                - search
                - text-editor
                - pdf-viewer
                - external
                - user-management
                - ocm
      
      - extraResources: 
        - |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: ocmproviders
            namespace: {{ "{{" }} template "ocis.namespace" . {{ "}}" }}
            labels:
              {{ "{{" }}- include "ocis.labels" . | nindent 4 {{ "}}" }}
          data:
            ocmproviders.json: |
              [
                {
                    "name": "oCIS Test",
                    "full_name": "oCIS Test provider",
                    "organization": "oCIS",
                    "domain": "ocis.kube.owncloud.test",
                    "homepage": "https://ocis.kube.owncloud.test",
                    "description": "oCIS Example cloud storage",
                    "services": [
                        {
                            "endpoint": {
                                "type": {
                                    "name": "OCM",
                                    "description": "ocis.kube.owncloud.test Open Cloud Mesh API"
                                },
                                "name": "ocis.kube.owncloud.test - OCM API",
                                "path": "https://ocis.kube.owncloud.test/ocm/",
                                "is_monitored": true
                            },
                            "api_version": "0.0.1",
                            "host": "http://ocis.kube.owncloud.test"
                        },
                        {
                            "endpoint": {
                                "type": {
                                    "name": "Webdav",
                                    "description": "ocis.kube.owncloud.test Webdav API"
                                },
                                "name": "ocis.kube.owncloud.test Example - Webdav API",
                                "path": "https://ocis.kube.owncloud.test/dav/",
                                "is_monitored": true
                            },
                            "api_version": "0.0.1",
                            "host": "https://ocis.kube.owncloud.test/"
                        }
                    ]
                },
                {
                    "name": "oCIS Test",
                    "full_name": "oCIS Test provider",
                    "organization": "oCIS",
                    "domain": "ocis2.kube.owncloud.test",
                    "homepage": "https://ocis2.kube.owncloud.test",
                    "description": "oCIS Example cloud storage",
                    "services": [
                        {
                            "endpoint": {
                                "type": {
                                    "name": "OCM",
                                    "description": "ocis2.kube.owncloud.test Open Cloud Mesh API"
                                },
                                "name": "ocis2.kube.owncloud.test - OCM API",
                                "path": "https://ocis2.kube.owncloud.test/ocm/",
                                "is_monitored": true
                            },
                            "api_version": "0.0.1",
                            "host": "http://ocis2.kube.owncloud.test"
                        },
                        {
                            "endpoint": {
                                "type": {
                                    "name": "Webdav",
                                    "description": "ocis2.kube.owncloud.test Webdav API"
                                },
                                "name": "ocis2.kube.owncloud.test Example - Webdav API",
                                "path": "https://ocis2.kube.owncloud.test/dav/",
                                "is_monitored": true
                            },
                            "api_version": "0.0.1",
                            "host": "https://ocis2.kube.owncloud.test/"
                        }
                    ]
                }
              ]


  - name: ocis2
    chart: ../../charts/ocis
    namespace: ocis2
    values:
      - externalDomain: ocis2.kube.owncloud.test
      - ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          tls:
            - secretName: ocis-dev-tls
              hosts:
                - ocis2.kube.owncloud.test

      - logging:
          level: debug

      - insecure:
          oidcIdpInsecure: true
          ocisHttpApiInsecure: true
          ocmInsecure: true

      - features:
          demoUsers: true
          ocm:
            enabled: true
            providersConfigRef: "ocmproviders"

      - services:
          idm:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          nats:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          search:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          storagesystem:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce

          storageusers:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
            maintenance:
              cleanUpExpiredUploads:
                enabled: true
                schedule: "* * * * *"
              purgeExpiredTrashBinItems:
                enabled: true
                schedule: "* * * * *"
              restartPostprocessing:
                enabled: true
                schedule: "* * * * *"

          thumbnails:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
            maintenance:
              cleanUpOldThumbnails:
                enabled: true
                schedule: "* * * * *"

          web:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
            config:
              apps:
                - files
                - search
                - text-editor
                - pdf-viewer
                - external
                - user-management
                - ocm
      - extraResources: 
        - |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: ocmproviders
            namespace: {{ "{{" }} template "ocis.namespace" . {{ "}}" }}
            labels:
              {{ "{{" }}- include "ocis.labels" . | nindent 4 {{ "}}" }}
          data:
            ocmproviders.json: |
              [
                {
                    "name": "oCIS Test",
                    "full_name": "oCIS Test provider",
                    "organization": "oCIS",
                    "domain": "ocis.kube.owncloud.test",
                    "homepage": "https://ocis.kube.owncloud.test",
                    "description": "oCIS Example cloud storage",
                    "services": [
                        {
                            "endpoint": {
                                "type": {
                                    "name": "OCM",
                                    "description": "ocis.kube.owncloud.test Open Cloud Mesh API"
                                },
                                "name": "ocis.kube.owncloud.test - OCM API",
                                "path": "https://ocis.kube.owncloud.test/ocm/",
                                "is_monitored": true
                            },
                            "api_version": "0.0.1",
                            "host": "http://ocis.kube.owncloud.test"
                        },
                        {
                            "endpoint": {
                                "type": {
                                    "name": "Webdav",
                                    "description": "ocis.kube.owncloud.test Webdav API"
                                },
                                "name": "ocis.kube.owncloud.test Example - Webdav API",
                                "path": "https://ocis.kube.owncloud.test/dav/",
                                "is_monitored": true
                            },
                            "api_version": "0.0.1",
                            "host": "https://ocis.kube.owncloud.test/"
                        }
                    ]
                },
                {
                    "name": "oCIS Test",
                    "full_name": "oCIS Test provider",
                    "organization": "oCIS",
                    "domain": "ocis2.kube.owncloud.test",
                    "homepage": "https://ocis2.kube.owncloud.test",
                    "description": "oCIS Example cloud storage",
                    "services": [
                        {
                            "endpoint": {
                                "type": {
                                    "name": "OCM",
                                    "description": "ocis2.kube.owncloud.test Open Cloud Mesh API"
                                },
                                "name": "ocis2.kube.owncloud.test - OCM API",
                                "path": "https://ocis2.kube.owncloud.test/ocm/",
                                "is_monitored": true
                            },
                            "api_version": "0.0.1",
                            "host": "http://ocis2.kube.owncloud.test"
                        },
                        {
                            "endpoint": {
                                "type": {
                                    "name": "Webdav",
                                    "description": "ocis2.kube.owncloud.test Webdav API"
                                },
                                "name": "ocis2.kube.owncloud.test Example - Webdav API",
                                "path": "https://ocis2.kube.owncloud.test/dav/",
                                "is_monitored": true
                            },
                            "api_version": "0.0.1",
                            "host": "https://ocis2.kube.owncloud.test/"
                        }
                    ]
                }
              ]


