apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocdav
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ocdav
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: ocdav
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: ocdav
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["ocdav", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: OCDAV_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: OCDAV_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: OCDAV_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: OCDAV_HTTP_ADDR
              value: 0.0.0.0:8080

            - name: OCDAV_PUBLIC_URL
              value: https://{{ .Values.externalDomain }}

            - name: REVA_GATEWAY
              value: gateway:9142
            - name: OCDAV_EVENTS_ENDPOINT
              value: nats:9233
            - name: OCDAV_EVENTS_TLS_INSECURE
              value: "true"
            - name: SEARCH_EVENTS_TLS_INSECURE
              value: "true"

            - name: OCDAV_INSECURE
              value: "{{ .Values.insecure.ocisHttpApiInsecure }}"

            - name: OCDAV_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            - name: OCDAV_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef }}
                  key: machine-auth-api-key

            - name: FORCE_RESCAN_PERIOD
              value: 12h

          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl --silent --fail http://localhost:9163/healthz
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
