apiVersion: v1
kind: Service
metadata:
  name: ocdav
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: ocdav
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: ocdav
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: metrics-debug
      port: 9163
      protocol: TCP
