{{- if not .Values.features.externalUserManagement.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: idm
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: idm
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: idm
  ports:
    - name: ldaps
      port: 9235
      protocol: TCP
{{- end }}
